[workspace]

members = [
    "ai_manager_service",
    "twitch_listener_service",
    "messages",
    "monolith",
    "kafka",
    "frontend_api",
    "user_service",
]

exclude = [
    "twitch_api"
]
