apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: twitch-alerts
  name: twitch-alerts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: twitch-alerts
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: twitch-alerts
    spec:
      containers:
      - image: twitch-alerts
        name: twitch-alerts
        resources: {}
status: {}
