apiVersion: apps/v1
kind: Deployment
metadata:
  name: twitch-alerts-frontend
  labels:
    app: twitch-alerts
spec:
  replicas: 1
  selector:
    matchLabels:
      lbtype: external
  template:
    metadata:
      labels:
        lbtype: external
        app: twitch-alerts
    spec:
      containers:
      - name: twitch-alerts
        image: nullchannel/twitch-alerts-frontend:0.1.4
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 1500m
            memory: "2Gi"
        ports:
        - containerPort: 8080
          name: frontend