apiVersion: v1
kind: Service
metadata:
  name: twitch-alerts
  namespace: twitch-alerts
  labels:
    app: twitch-alerts
spec:
  ports:
    - port: 9000
      name: http
    - port: 9090
      name: metrics
  selector:
    app: twitch-alerts