apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: twitch-alert-service
  name: twitch-alert-service
spec:
  ports:
  - name: "8080"
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: twitch-alert-service
  type: LoadBalancer
status:
  loadBalancer: {}
