apiVersion: v1
kind: Service
metadata:
  name: twitch-alerts-0
spec:
  type: LoadBalancer
  selector:
    statefulset.kubernetes.io/pod-name: twitch-alerts-0
  ports:
  - protocol: TCP
    port: 9000
    targetPort: 9000
    name: http
