[package]
name = "messages"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.68"
anyhow = "1.0.51"
serde = {version = "1.0.163", features = ["derive"]}
serde_json = "1.0.96"