[package]
name = "kafka"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = "../common" }
rdkafka = "0.29.0"
twitch_api = {path = "../twitch_api", features = ["eventsub"]}